# Taken from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          name: Install Python
          with:
            python-version: '3.9'

        - name: Build sdist
          run: python setup.py sdist

        - uses: actions/upload-artifact@v2
          with:
            path: dist/*.tar.gz

  upload_pypi:
      needs: [build_sdist]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/download-artifact@v2
            with:
              name: artifact
              path: dist

          - uses: pypa/gh-action-pypi-publish@v1.4.2
            with:
              user: armand33
              password: ${{ secrets.TWINE_PASSWORD }}